version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - AUTO_UPDATE=true
    volumes:
      - ./config:/config/Jackett
    ports:
      - 9117:9117
    restart: unless-stopped
